<?php
$db_host="localhost";
$db_user="root";
$db_pass="";
$db_name="test";
$api_key='apikey';
$api_secret='apisecret';
$admin_token='admintoken';
$token_secret='tokensecret';
$url="http://localhost/socialstream"
?>
